spring:
  config:
    activate:
      on-profile: local
  mail:
    host: ${NCP_MAIL_HOST}         # 네이버 SMTP 서버 주소
    port: 465                    # 네이버 SMTP 포트 번호
    username: ${NCP_EMAIL}    # 네이버 이메일
    password: ${NCP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          ssl:
            enable: true
            trust: smtp.naver.com

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username:  ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      key:
        prefix:
          refreshToken: "refreshToken:"
          blacklist: "blacklist:"
          accessToken: "access_token"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 30
  refresh-expiration: 10080


  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${FEIGN_CONNECT_TIMEOUT}
            readTimeout: ${FEIGN_READ_TIMEOUT}
            loggerLevel: ${FEIGN_LOGGER_LEVEL}


oauth:
  google:
    android:
      client-id: ${ANDROID_CLIENT_ID}
      redirect-uri: ${ANDROID_REDIRECT_URI}
    ios:
      client-id: ${IOS_CLIENT_ID}
      redirect-uri: ${IOS_REDIRECT_URI}
    web:
      client-id: ${WEB_CLIENT_ID}
      client-secret: ${WEB_CLIENT_SECRET}
      redirect-uri: ${WEB_REDIRECT_URI}

  apple:
    team-id: ${APPLE_TEAM_ID}
    key-id: ${APPLE_KEY_ID}
    client-id: ${APPLE_CLIENT_ID}
    redirect-uri: ${APPLE_REDIRECT_URI}
    private-key-pem: |-
      ${APPLE_PRIVATE_KEY_PEM}

ncp:
  s3:
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    bucket: ${NCP_BUCKET}


swagger:
  server-url: http://localhost:8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

google:
  cloud:
    project:
      id: ${GCP_PROJECT_ID}
    translate:
      api-key: ${GCP_TRANSLATE_API_KEY}

app:
  mail:
    from: ${NAVER_HOST}         # 보내는 주소(네이버 계정과 동일 권장)
    brand: ${APP_NAME}                    # 메일 제목/본문에 쓸 브랜드명
    code-ttl-minutes: 3

