spring:
  config:
    activate:
      on-profile: main

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false   # ★ 이 줄 추가
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  datasource:
    url: jdbc:postgresql://${DB_DOMAIN}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_DOMAIN}:27017/${MONGO_INITDB_DATABASE}?authSource=admin

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      key:
        prefix:
          refreshToken: "refreshToken:"
          blacklist: "blacklist:"
          accessToken: "access_token"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 10080
  refresh-expiration: 10080



app:
  search:
    es-url: ${ES_URL}
main:
  service:
    url: ${MAIN_URL}
server:
  port: 8081

