name: diagnostic
on:
  workflow_dispatch: {}
  push:
    branches: ["dev"]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "OK - workflow triggered"
